name: Weekly Discord Report

on:
  schedule:
    - cron: '40 12 * * 4'  # 每週四 台灣時間晚上 8:50
  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"⏰ 今天是星期四，記得新增下週的開獎期數\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
